{
  "id": "error",
  "expressionLang": "jsonpath",
  "version": "1.0",
  "name": "Workflow Error example",
  "description": "An example of how to handle an exception thrown by a service",
  "start": "checkEven",
  "errors": [{
          "name": "odd number",
          "code": "java.lang.IllegalArgumentException"
        }],
  "functions": [
    {
      "name": "isEven",
      "type": "custom",
      "operation": "service:org.kie.kogito.examples.EvenService::isEven"
    },
    {
      "name": "printMessage",
      "type": "custom",
      "operation": "sysout"
    }
  ],
  "states": [
    {
      "name": "checkEven",
      "type": "operation",
      "actions": [
        {
          "name": "checkEvenAction",
          "functionRef": {
            "refName": "isEven",
            "arguments": {
              "number": "$.number"
            }
          }
        }
      ],
      "transition": "even",
      "onErrors": [ {
        "errorRef" : "odd number",   
        "transition": "odd" }
      ]
    },
    {
      "name": "even",
      "type": "inject",
      "data": {
        "numberType": "even"
      },
      "transition": "finish"
    },
    {
      "name": "odd",
      "type": "inject",
      "data": {
        "numberType": "odd"
      },
      "transition": "finish"
    },
    {
      "name": "finish",
      "type": "operation",
      "actions": [
        {
          "name": "printAction",
          "functionRef": {
            "refName": "printMessage",
            "arguments": {
              "message": "$.numberType"
            }
          }
        }
      ],
      "end": {
        "terminate": "true"
      }
    }
  ]
}